# Generated by Django 4.2.5 on 2023-10-24 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("applicompte", "0001_initial"),
        ("applipizza", "0003_pizza_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commande",
            fields=[
                ("idCommande", models.AutoField(primary_key=True, serialize=False)),
                ("dateCommande", models.DateTimeField(auto_now_add=True)),
                ("payee", models.BooleanField(default=False)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "pizzauser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applicompte.pizzauser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LigneCommande",
            fields=[
                (
                    "idLigneCommande",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("quantite", models.PositiveIntegerField()),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applipanier.commande",
                    ),
                ),
                (
                    "pizza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applipizza.pizza",
                    ),
                ),
            ],
        ),
    ]
