# Generated by Django 4.2.5 on 2023-10-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applipanier", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="prix",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
